name: Deploy
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
    branches: [master]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PLAYGROUND_S3_BUCKET: s3://d2lang-playground-278852893615
  PLAYGROUND_CLOUDFRONT_ID: E1RNQAJ339Z6K4

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::278852893615:role/d2lang-playground-deploy
          aws-region: us-west-1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y brotli minify
          npm install -g esbuild
      - name: Install JavaScript dependencies
        run: |
          cd src/js
          yarn install
      - name: Deploy to production
        run: ./ci/deploy.sh
